.PHONY: build clean

build: clock.c hello.c infinities.c env_var.c argu.c
	gcc clock.c -o clock
	gcc hello.c -o hello
	gcc infinities.c -o infinities
	gcc env_var.c -o env_var
	gcc argu.c -o argu

clean: 
	rm -rf clock hello infinities env_var argu
